import axios from "axios";

const backendUrl = "https://expense-tracker-app-8cf1e-default-rtdb.europe-west1.firebasedatabase.app";

export function getHttpErrorMessage(error) {
  if (error.response) {
    return "The server could not complete the request. Please try again.";
  }

  if (error.request) {
    return "Could not connect to the server. Check your internet connection.";
  }

  return "Something went wrong. Please try again shortly.";
}

export async function storeExpense(expenseData) {
  const response = await axios.post(
    `${backendUrl}/expenses.json`,
    expenseData
  ) // id will be automatically generated by firebase so we don't need to send it in the request body
  const id = response.data.name; // firebase will return the generated id in the response body under the name property
  return id;
}

export async function fetchExpenses() {
  const response = await axios.get(`${backendUrl}/expenses.json`);
  const expenses = [];
  for (const key in response.data) {
    expenses.push({
      id: key,
      ...response.data[key],
      date: new Date(response.data[key].date),
    });
  } // check firebase db schema for the structure of the data. The data is stored as an object with keys as the id and values as the expense data. So we need to loop through the keys and push the expense data into an array.
  return { data: expenses };
}

export async function updateExpense(id, expenseData) {
  await axios.put(`${backendUrl}/expenses/${id}.json`, expenseData);
}

export async function deleteExpense(id) {
  await axios.delete(`${backendUrl}/expenses/${id}.json`);
}